# Generated by Django 3.0 on 2019-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
