# Generated by Django 3.0 on 2019-12-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='json_map',
            field=models.TextField(default=('NORTH',)),
            preserve_default=False,
        ),
    ]
