# Generated by Django 3.0.1 on 2020-01-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_map_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='map_exits_input',
            field=models.TextField(default='0, 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='map_start_input',
            field=models.TextField(default='0,0'),
            preserve_default=False,
        ),
    ]
