# Generated by Django 3.0 on 2020-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20200117_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='health',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
