# Generated by Django 3.0 on 2020-01-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='map_input',
        ),
    ]
