# Generated by Django 3.0.1 on 2020-01-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_map_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='map_exits_input',
        ),
        migrations.RemoveField(
            model_name='task',
            name='map_start_input',
        ),
    ]
